require('core/setup')
require('modeling/setup')
require('modeling-hedera/setup')
require('storage-hedera/setup')
require('wiki-hedera/setup')
require('jwt-hedera/setup')
require('shared/types')
require('hedera/setup')
require('core-hedera/index')
require('./global')


require('hedera')
require('management-hedera')
require('storage-hedera')
require('modeling-hedera')