require('core/setup')
require('modeling/setup')
require('modeling-hedera/setup')
require('ressourcing/setup')
require('storage/setup')
require('storage-hedera/setup')
require('./modeling/setup')
require('management-hedera/setup')
require('wiki-hedera/setup')
require('jwt-hedera/setup')
require('starbor-shared/types')
require('hedera/setup')
require('core-hedera/index')
require('./global')

require('jwt/setup')

require('hedera')
require('management-hedera')
require('storage-hedera')
require('modeling-hedera')